### ISSUE TITLE
[Question] XIEvent Type

### ISSUE THREAD

**Issue by jamesbradleym** [atom0s/XiEvents#1]
Hello! First off I want to say thank you for the work you've done here in establishing a structure for the XIEvent Dats, It's been a tremendous (read: I could not have done this without you 😂) help! I've been tinkering with xi-tinkerer and made a fork that implements a round trip from .dat to .yml for events. 

Now I'm at the point where I'm trying to determine how to make this useful, such as having the .yml include human-readable info, but to do so I'd need to know that the immid data is of a certain type.

For example, how might I know what immed_data 30 is below, or that 8033 is a string id? Why are index 0, 1, and 2 event_exec_nums the max value of unsigned 16-bit integer? Where should I be looking for event 271? What can I do with the event_data bytes? This is my first foray into decoding and investigating .dat files so I may be missing something obvious for how to decipher this but figured I'd ask first before going into fruitless rabbit holes.

Thanks again!

https://github.com/jamesbradleym/xi-tinkerer/tree/event

```
actor_number: 17764522
  tag_count: 4
  tag_offsets:
  - 0
  - 1
  - 2
  - 11
  event_exec_nums:
  - 65535
  - 65535
  - 65535
  - 271
  immed_count: 2
  immed_data:
  - 30
  - 8033
  event_data_size: 26
  event_data:
  - 0
  - 0
  - 94
  - 105
  - 100
  - 108
  - 48
  - 28
  - 0
  - 128
  - 0
  - 30
  - 240
  - 255
  - 255
  - 127
  - 111
  - 112
  - 29
  - 1
  - 128
  - 35
  - 32
  - 0
  - 33
  - 0
  - 255
  - 255
  ```
